# This file holds the configs for the linters, and it should be placed in the current working directory.
version: "2"
run:
  go: 1.22.1
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    # Reference doc with available linters and description for the linters below: https://golangci-lint.run/usage/linters/
    # Default
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Bug linters
    - errorlint
    - gosec
    - gosmopolitan
    - nilerr
    - testifylint

    # Comment linters
    - godot

    # Complexity linters
    - cyclop
    - funlen
    - gocognit
    - gocyclo
    - nestif

    # Meta linters
    - gocritic
    - revive
    - staticcheck

    # Style linters
    - copyloopvar
    - dogsled
    - dupl
    - errname
    - forcetypeassert
    - gochecknoinits
    - goconst
    - goheader
    - inamedparam
    - ireturn
    - lll
    - makezero
    - misspell
    - mnd
    - nilnil
    - nlreturn
    - nonamedreturns
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace

    # Test linters
    - ginkgolinter
    - testableexamples
    - testpackage
  settings:
    lll:
      line-length: 100
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: _test\.go
        text: 'dot-imports: should not use dot imports'
      - linters:
          - goconst
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # Default values allow for the showing of only 50 issues.
  # Setting it to 0 disables the default config and shows all issues at once.
  max-issues-per-linter: 0
  # Default values allow showing only 3 repeating issues.
  # Setting it to 0 disables the default config and shows all repeating issues at once.
  max-same-issues: 0
formatters:
  enable:
    # Format linters.
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
