name: Run Tests

on: pull_request

jobs:
  build:
    # Prevents the workflow from running on non-human triggers.
    if: github.actor != 'github-actions[bot]'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up Go Environment
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.12.2
          args: ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Run Fuzz Tests
        run: |
          go test -run=^$ -fuzz=FuzzCutIndent -fuzztime=5s ./indent
          go test -run=^$ -fuzz=FuzzPatternFindIn -fuzztime=5s ./embedding/parsing

      - name: Run E2E Tests
        run: go test -v -tags showcase ./showcase
