name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # Prevents the workflow from running on non-human triggers.
    if: github.actor != 'github-actions[bot]'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Run Tests
        # Tests must be run sequentially because they create temporary files that can cause issues.
        # Therefore, the "-p 1" argument is required.
        run: go test -v ./... -p 1
